spring:
  cloud:
    gateway:
      routes:
        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter


#        - id: restaurant-service
#          uri: lb://RESTAURANT-SERVICE
#          predicates:
#            - Path=/restaurant/**
#          filters:
#            - AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/