spring:
  application:
    name: user-service
  kafka:
    consumer:
      group-id: "default"


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 8300

topic:
  name: t.user.cred
