spring:
  cloud:
    config:
      server:
        git:
          uri: D:\Java\app-config-server
#          username: neevels@mail.ru
#          password: byNevels0214
        default-label: master
  application:
    name: config-server
server:
  port: 8888

#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/
